### ISSUE TITLE
category表 自增id的问题 

### ISSUE THREAD

**Issue by takyee** [Kaciras/ClosureTable#1]
建  category 表的时候id 字段选择了 `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,

INSERT INTO `category` (`id`, `name`) VALUES (0, 'root'); 这句应该不生效了，那后面的逻辑中找ID为0的是根组件，回收影响吗？

**Comment by Xhandsomeman** [comment]
如果几百万类别，能够承受吗

**Comment by Kaciras** [comment]
额……已解决。

这项目写完就没管了，今天才发现有个 Issue。
